"""Add notes field to savings goals

Revision ID: 144b3ee1cad0
Revises: 936ba44da765
Create Date: 2026-08-26 12:29:44.516101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144b3ee1cad0'
down_revision: Union[str, Sequence[str], None] = '936ba44da765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_goals', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_goals', 'notes')
    # ### end Alembic commands ###
